package org.glygen.array.client.model;

public enum LinkerType {
	SMALLMOLECULE,
	LIPID,
	PEPTIDE,
	PROTEIN, 
	OTHER,
	UNKNOWN_SMALLMOLECULE,
	UNKNOWN_LIPID,
	UNKNOWN_PEPTIDE,
	UNKNOWN_PROTEIN,
	UNKNOWN_OTHER
}
